### PR TITLE
Add support for using ArcGIS_WaitForComponent multiple times in single configuration.

### PR DESCRIPTION
**Pull request by PleaseStopAsking**
When using the ArcGIS_WaitForComponent resource, there are scenarios where it would fail due to the Keys not being unique enough. An example is when waiting for multiple Server machines to become available through their web adaptors that have different web adaptor contexts (server1, server2, etc), before federating those Servers.

I understand this could be "hacked" around by specifying another InvokingComponent as that is currently not utilized in the code but by making the ComponentContext as Key, it provides a valid solution since the ComponentContext parameter is required anyway.

Example that fails before making the ComponentContext a Key...
```
ArcGIS_WaitForComponent "hostingServer" {
	Component = "ServerWA"
	InvokingComponent = "Portal"
	ComponentHostName = $externalDNS
	ComponentContext = "hosted"
	Ensure = "Present"
	Credential = $arcgisAdminCredential
	RetryIntervalSec = 60
	RetryCount = 60
	DependsOn = $Depends
}
$Depends += "[ArcGIS_WaitForComponent]hostingServer"

ArcGIS_WaitForComponent "gisServer" {
	Component = "ServerWA"
	InvokingComponent = "Portal"
	ComponentHostName = $externalDNS
	ComponentContext = "server"
	Ensure = "Present"
	Credential = $arcgisAdminCredential
	RetryIntervalSec = 60
	RetryCount = 60
	DependsOn = $Depends
}
$Depends += "[ArcGIS_WaitForComponent]gisServer"
```

### CODE REVIEW

**Comment by shailesh91** [comment]
@PleaseStopAsking is your use case when you are trying to configure hosted server and server with other server roles as part of one config?

**Comment by PleaseStopAsking** [comment]
@shailesh91 Correct. If we have a single config that handles all Server roles as well as Datastore and Portal, having the ability to wait for all the Servers to become available through their respective web adaptors is very useful if we need to federate both the services URL and Admin Url through the web adaptor endpoint.

**Web Adaptor Contexts**

```
GIS_Server_Context = 'server'
Hosting_Server_Context = 'hosted'
Image Server_Context = 'image'
```

**Comment by shailesh91** [comment]
@PleaseStopAsking this is a valid use case. But, this change will affect DSC configurations. I will try to merge it after V2 release next week.

**Comment by shailesh91** [comment]
@PleaseStopAsking Can you resubmit this PR without the fix for #154. Thanks!

**Pull request merged**
