### PR TITLE
Config for ArcGIS Enterprise on Disconnected Environment

### PR DESCRIPTION
**Pull request by spitzerr**
See #26

### CODE REVIEW

**Comment by shailesh91** [comment]
@spitzerr Can you tell me the Implementation details and steps for DisconnectedEnvironment for Portal?

**Comment by shailesh91** [comment]
@spitzerr any reason you think the DisconnectedEnvironment should be a different Configuration, instead of being a part of the ArcGISConfigure Configuration?

**Comment by spitzerr** [comment]
@shailesh91 I've done this for two reasons

1. All the things about the disconnected Environment have to be done after the stuff like federation and registration, which is done in ArcGISConfigure
2. The ArcGISConfigure Part is already very bloated and there are many distinct cases like WA yes/no; Multimachine and so on. I thought it would be straight forward to get this things done seperately or even miss them if it's not wanted by user

**Comment by spitzerr** [comment]
@shailesh91 about disconnected Portal we follow this dosumentation:
http://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-a-disconnected-deployment.htm
As we are already developing some of these things I'd love to arrange the next steps with you

**Comment by shailesh91** [comment]
@spitzerr I think this should be part of the ArcGISConfigure since this step is not a post-deployment operation and is a step in the configuration of ArcGIS Enterprise. 
Ideally, it should use the waitfor resource and wait for Federation to happen in Server Switch Block and should happen only the Primary Server Node. Handling the distinct cases should not be that much of an issue.

**Comment by shailesh91** [comment]
@spitzerr For the disconnected Portal, I will read the doc. And sure it would be great if we could talk about the next steps for this part.

**Comment by spitzerr** [comment]
@shailesh91 

> Ideally, it should use the waitfor resource and wait for Federation to happen in Server Switch Block 

Totally agree on this.

>  and should happen only the Primary Server Node.

I disagree on this. As the Primary Server Node could fail in Service, it should be deployed on every Server machine. Shouldn't it?

**Comment by shailesh91** [comment]
@spitzerr since we are working with the admin api, even if the primary server service fails the Config Store is already updated. The settings of disconnected enviornment are applicable even on the other servers in the deployment. 
Just to clarify you are talking about the server service failure after the Dsc Configuration has completed successfully, right?

**Comment by spitzerr** [comment]
@shailesh91 Yes agreed.

**Comment by shailesh91** [comment]
Merged this Pull Request with #41

**Pull request closed without merging**
