### PR TITLE
Fix EnableDebugLogging; Test for Logging in HAPortal;Wait for Token-Url

### LINKED ISSUE #13: Test for non-HAPortal always false
The Test for Correct Portal Configuration is always false. As Test checks of wrong loglevels on Catalina which are only set for HA-Portal.

### PR DESCRIPTION
**Pull request by spitzerr**
Fixes #13

### CODE REVIEW

**Comment by spitzerr** [comment]
@shailesh91 could you please review this one as well?

**Comment by shailesh91** [comment]
@spitzerr There is no variable named $DebugMode in ArcGISConfigure.ps1. Can you please change it to $ConfigurationData.ConfigData.DebugMode and resubmit the PR. Thanks.

**Comment by spitzerr** [comment]
@shailesh91 good catch thank you. Changed it. Could you please review again?

**Comment by shailesh91** [comment]
@spitzerr I think instead of adding test log level on Catalina only if HaPortal, we should set log level on Catalina in Set-TargetResource if EnableDebugLogging is "true" or if it is HaPortal [Line 401](https://github.com/Esri/arcgis-powershell-dsc/blob/0dbe67683121557b33bcc6eae778a7df602a6968/Modules/ArcGIS/DSCResources/ArcGIS_Portal/ArcGIS_Portal.psm1#L401). That would be a better use of the EnableDebugLogging Flag. 
As a result of the above modification, an OR condition to check for HAPortal will have to be added [Line 733](https://github.com/Esri/arcgis-powershell-dsc/blob/0dbe67683121557b33bcc6eae778a7df602a6968/Modules/ArcGIS/DSCResources/ArcGIS_Portal/ArcGIS_Portal.psm1#L733)

**Comment by spitzerr** [comment]
@shailesh91 agree.
I'm currently not able to modify PR but it should be writeable to you. Could you maybe fix this one?

**Comment by shailesh91** [comment]
@spitzerr 
``` if (Set-LoggingLevel -EnableDebugLogging $false) { $RestartRequired = $true}```
Do you mean the above needs to be added to the else condition in case the  EnableDebugLogging is "false" and it is not a HAPortal [Line 408](https://github.com/Esri/arcgis-powershell-dsc/blob/0dbe67683121557b33bcc6eae778a7df602a6968/Modules/ArcGIS/DSCResources/ArcGIS_Portal/ArcGIS_Portal.psm1#L408) ?

**Comment by spitzerr** [comment]
@shailesh91 yes exactly.
As it gets checked for "normal" loglevel in Test-TargetRessource on else-condition L736 it should be set to this level in Set-TargetRessource, shouldn't it?

**Comment by shailesh91** [comment]
@spitzerr agreed! Making necessary changes.

**Pull request merged**
