### PR TITLE
Register additional server dirs

### PR DESCRIPTION
**Pull request by spitzerr**
especially for additional Cache-Directories. Eg. it is not necessary to copy already prepared Caches to new Location. Instead Register These Folders in Server.

### CODE REVIEW

**Comment by shailesh91** [comment]
@spitzerr looks good. Seems low risk, will verify and merge sometime next week.

**Comment by shailesh91** [comment]
@spitzerr these dirs need to be given runAs user permission. Are you assuming that the user will manually give them?

**Comment by spitzerr** [comment]
@shailesh91 
we did this for "already there" data which should not be copied due to big data. On our site its alway on "external" file-Shares. These permissions must be set manually.
For most flexibility you could extent this to set permissions automatically if its local dirs.

**Comment by shailesh91** [comment]
@spitzerr I will have work on the setting permissions on local dir part and merge it.

**Comment by shailesh91** [comment]
Creating a separate issue for handling permissions on local dirs. #54

**Pull request merged**
